/* The following code was generated by JFlex 1.4.1 on 5/13/09 1:45 PM */

package parser;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 5/13/09 1:45 PM from the specification file
 * <tt>C:/Help/Alexey/My New Projects/Eclipse Projects/SparkLogo/jflex/SparkLogo.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 1;
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  2,  0,  3,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3,  6, 44, 15, 16,  6,  6, 45, 35, 36, 17, 12, 43,  8, 10,  6, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 41,  4,  6, 42,  6,  6, 
    14,  5,  5,  5,  5, 11,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 
     5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 37, 13, 38,  6,  7, 
     0, 27, 26, 32, 20, 18, 21, 24, 29,  5,  5,  5, 25, 33, 19, 22, 
    34,  5, 23, 28, 31,  5, 30,  5,  5,  5,  5, 39,  0, 40,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\3\2\1\3\2\4\1\5\1\6\1\7"+
    "\1\4\11\3\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\1\1\23\1\0"+
    "\1\5\2\0\1\4\7\3\1\24\2\3\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\0\1\5"+
    "\1\0\1\4\1\35\1\36\4\3\1\37\2\3\2\0"+
    "\6\3\2\0\1\3\1\40\1\3\1\41\1\42\1\43"+
    "\2\0\1\44\1\45\4\0\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\134\0\270\0\346\0\u0114"+
    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284"+
    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\134\0\134"+
    "\0\134\0\134\0\134\0\134\0\134\0\u0114\0\134\0\134"+
    "\0\u03c6\0\u03f4\0\134\0\u019e\0\u0422\0\u0450\0\u047e\0\u04ac"+
    "\0\u04da\0\u0508\0\u0536\0\u0564\0\u0592\0\u05c0\0\u05ee\0\346"+
    "\0\u061c\0\u064a\0\134\0\134\0\134\0\134\0\134\0\134"+
    "\0\134\0\134\0\u0678\0\u0678\0\u06a6\0\u06d4\0\346\0\346"+
    "\0\u0702\0\u0730\0\u075e\0\u078c\0\346\0\u07ba\0\u07e8\0\u0816"+
    "\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986"+
    "\0\u09b4\0\u09e2\0\346\0\u0a10\0\346\0\346\0\346\0\u0a3e"+
    "\0\u0a6c\0\346\0\346\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\134";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\13\1\7\1\10\1\3\1\14\2\3\1\15"+
    "\1\16\2\7\1\17\2\7\1\20\2\7\1\21\1\22"+
    "\1\7\1\23\1\24\1\25\1\26\1\7\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\3\1\41\1\3\1\0\12\41\1\42\36\41\1\43"+
    "\1\41\60\0\1\5\53\0\1\6\1\4\1\5\53\6"+
    "\5\0\1\7\1\0\3\7\1\0\1\7\6\0\21\7"+
    "\21\0\1\10\1\0\1\10\3\0\1\10\4\0\1\10"+
    "\30\0\1\10\11\0\1\10\1\0\1\10\1\12\1\44"+
    "\1\0\1\10\4\0\1\10\30\0\1\10\14\0\1\12"+
    "\1\45\1\46\6\0\1\46\44\0\1\45\63\0\1\47"+
    "\44\0\1\10\1\0\1\10\3\0\1\10\4\0\1\50"+
    "\30\0\1\10\10\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\1\7\1\51\17\7\20\0\1\7\1\0\3\7"+
    "\1\0\1\7\6\0\4\7\1\52\14\7\20\0\1\7"+
    "\1\0\3\7\1\0\1\7\6\0\7\7\1\53\11\7"+
    "\20\0\1\7\1\0\3\7\1\0\1\7\6\0\6\7"+
    "\1\54\12\7\20\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\13\7\1\55\4\7\1\56\20\0\1\7\1\0"+
    "\3\7\1\0\1\7\6\0\11\7\1\57\7\7\20\0"+
    "\1\7\1\0\3\7\1\0\1\7\6\0\4\7\1\60"+
    "\14\7\20\0\1\7\1\0\3\7\1\0\1\7\6\0"+
    "\7\7\1\61\11\7\20\0\1\7\1\0\3\7\1\0"+
    "\1\7\6\0\4\7\1\62\14\7\13\0\1\41\2\0"+
    "\12\41\1\0\36\41\1\0\1\41\15\0\1\63\5\0"+
    "\1\64\1\0\1\65\1\0\1\66\2\0\1\67\4\0"+
    "\1\70\14\0\1\71\1\72\11\0\1\45\1\0\1\46"+
    "\6\0\1\46\43\0\1\73\1\74\2\0\1\73\61\0"+
    "\1\75\43\0\1\10\1\0\1\10\3\0\1\10\4\0"+
    "\1\76\30\0\1\10\10\0\1\7\1\0\3\7\1\0"+
    "\1\7\6\0\2\7\1\77\16\7\20\0\1\7\1\0"+
    "\3\7\1\0\1\7\6\0\5\7\1\100\13\7\20\0"+
    "\1\7\1\0\3\7\1\0\1\7\6\0\4\7\1\101"+
    "\14\7\20\0\1\7\1\0\3\7\1\0\1\7\6\0"+
    "\1\102\20\7\20\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\11\7\1\103\7\7\20\0\1\7\1\0\3\7"+
    "\1\0\1\7\6\0\11\7\1\104\7\7\20\0\1\7"+
    "\1\0\3\7\1\0\1\7\6\0\5\7\1\105\13\7"+
    "\20\0\1\7\1\0\3\7\1\0\1\7\6\0\11\7"+
    "\1\106\7\7\20\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\2\7\1\107\16\7\24\0\1\74\63\0\1\110"+
    "\44\0\1\10\1\0\1\10\3\0\1\10\4\0\1\10"+
    "\1\111\27\0\1\10\10\0\1\7\1\0\3\7\1\0"+
    "\1\7\6\0\10\7\1\112\10\7\20\0\1\7\1\0"+
    "\3\7\1\0\1\7\6\0\1\7\1\113\17\7\20\0"+
    "\1\7\1\0\3\7\1\0\1\7\6\0\5\7\1\114"+
    "\13\7\20\0\1\7\1\0\3\7\1\0\1\7\6\0"+
    "\16\7\1\115\2\7\20\0\1\7\1\0\3\7\1\0"+
    "\1\7\6\0\12\7\1\116\6\7\20\0\1\7\1\0"+
    "\3\7\1\0\1\7\6\0\1\117\20\7\31\0\1\120"+
    "\62\0\1\121\37\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\11\7\1\122\7\7\20\0\1\7\1\0\3\7"+
    "\1\0\1\7\6\0\15\7\1\123\3\7\20\0\1\7"+
    "\1\0\3\7\1\0\1\7\6\0\1\124\20\7\20\0"+
    "\1\7\1\0\3\7\1\0\1\7\6\0\1\125\20\7"+
    "\20\0\1\7\1\0\3\7\1\0\1\7\6\0\12\7"+
    "\1\126\6\7\20\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\7\7\1\127\11\7\32\0\1\130\62\0\1\131"+
    "\36\0\1\7\1\0\3\7\1\0\1\7\6\0\7\7"+
    "\1\132\11\7\20\0\1\7\1\0\3\7\1\0\1\7"+
    "\6\0\2\7\1\133\16\7\33\0\1\134\56\0\1\135"+
    "\53\0\1\136\57\0\1\137\52\0\1\140\60\0\1\140"+
    "\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2898];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\21\1\7\11\1\1\2\11"+
    "\2\1\1\11\1\0\1\1\2\0\13\1\10\11\1\0"+
    "\1\1\1\0\12\1\2\0\6\1\2\0\6\1\2\0"+
    "\2\1\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
 // private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  //private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  	StringBuffer string = new StringBuffer();
	public Scanner(java.io.InputStream r, SymbolFactory sf){
		this(r);
		this.sf = sf;
	}
	
	private SymbolFactory sf;
	
	private Symbol lastSymbol;
	
	public Symbol peekToken() throws java.io.IOException {
		if (lastSymbol != null)
			return lastSymbol;
		else
			return lastSymbol = get_token();
	}
	
	public Symbol nextToken() throws java.io.IOException {
		if (lastSymbol != null) {
			Symbol tmp = lastSymbol;
			lastSymbol = null;
			return tmp;
		}
		
		return get_token();
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
//    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = /*yychar =*/ yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol get_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { return sf.newSymbol("DOT", sym.DOT, yyline, yycolumn);
          }
        case 39: break;
        case 36: 
          { return sf.newSymbol("global", sym.GLOBAL, yyline, yycolumn);
          }
        case 40: break;
        case 23: 
          { string.append( '\f' );
          }
        case 41: break;
        case 16: 
          { return sf.newSymbol("COMMA", sym.COMMA, yyline, yycolumn);
          }
        case 42: break;
        case 19: 
          { yybegin(YYINITIAL); return sf.newSymbol("STRING", sym.STRING, string.toString(), yyline, yycolumn);
          }
        case 43: break;
        case 8: 
          { return sf.newSymbol("LPAREN", sym.LPAREN, yyline, yycolumn);
          }
        case 44: break;
        case 37: 
          { return sf.newSymbol("shared", sym.SHARED, yyline, yycolumn);
          }
        case 45: break;
        case 20: 
          { return sf.newSymbol("to", sym.TO, yyline, yycolumn);
          }
        case 46: break;
        case 34: 
          { return sf.newSymbol("class", sym.CLASS, yyline, yycolumn);
          }
        case 47: break;
        case 25: 
          { string.append( '\b' );
          }
        case 48: break;
        case 4: 
          { return sf.newSymbol("OPERATOR", sym.OPERATOR, yytext(), yyline, yycolumn);
          }
        case 49: break;
        case 26: 
          { string.append( '\t' );
          }
        case 50: break;
        case 28: 
          { string.append( '\'' );
          }
        case 51: break;
        case 30: 
          { return sf.newSymbol("for", sym.FOR, yyline, yycolumn);
          }
        case 52: break;
        case 33: 
          { return sf.newSymbol("space", sym.SPACE, yyline, yycolumn);
          }
        case 53: break;
        case 14: 
          { return sf.newSymbol("COLON", sym.COLON, yyline, yycolumn);
          }
        case 54: break;
        case 11: 
          { return sf.newSymbol("RBRACK", sym.RBRACK, yyline, yycolumn);
          }
        case 55: break;
        case 35: 
          { return sf.newSymbol("model", sym.MODEL, yyline, yycolumn);
          }
        case 56: break;
        case 3: 
          { return sf.newSymbol("IDENTIFIER", sym.IDENTIFIER, yytext(), yyline, yycolumn);
          }
        case 57: break;
        case 5: 
          { return sf.newSymbol("DOUBLE", sym.DOUBLE, new Double(yytext()), yyline, yycolumn);
          }
        case 58: break;
        case 10: 
          { return sf.newSymbol("LBRACK", sym.LBRACK, yyline, yycolumn);
          }
        case 59: break;
        case 29: 
          { return sf.newSymbol("end", sym.END, yyline, yycolumn);
          }
        case 60: break;
        case 7: 
          { return sf.newSymbol("@", sym.ANNOTATION, yyline, yycolumn);
          }
        case 61: break;
        case 27: 
          { string.append( '\"' );
          }
        case 62: break;
        case 32: 
          { return sf.newSymbol("agent", sym.AGENT, yyline, yycolumn);
          }
        case 63: break;
        case 24: 
          { string.append( '\r' );
          }
        case 64: break;
        case 13: 
          { return sf.newSymbol("RBRACE", sym.RBRACE, yyline, yycolumn);
          }
        case 65: break;
        case 17: 
          { yybegin(STRING); string.setLength(0);
          }
        case 66: break;
        case 21: 
          { string.append( '\\' );
          }
        case 67: break;
        case 1: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 68: break;
        case 15: 
          { return sf.newSymbol("EQ", sym.EQ, yyline, yycolumn);
          }
        case 69: break;
        case 22: 
          { string.append( '\n' );
          }
        case 70: break;
        case 31: 
          { return sf.newSymbol("var", sym.VAR, yyline, yycolumn);
          }
        case 71: break;
        case 9: 
          { return sf.newSymbol("RPAREN", sym.RPAREN, yyline, yycolumn);
          }
        case 72: break;
        case 18: 
          { string.append( yytext() );
          }
        case 73: break;
        case 38: 
          { return sf.newSymbol("EOF", sym.EOF, yyline, yycolumn);
          }
        case 74: break;
        case 12: 
          { return sf.newSymbol("LBRACE", sym.LBRACE, yyline, yycolumn);
          }
        case 75: break;
        case 2: 
          { 
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return sf.newSymbol("EOF", sym.EOF, -1, -1);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
