
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 20 10:50:50 EDT 2008
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AGENT = 1000;
  public static final int MODEL = 1001;
  public static final int SPACE = 1002;
  public static final int ANNOTATION = 1003;
  public static final int SHARED = 1004;
  public static final int FOR = 1005;
  public static final int CLASS = 1006;
  public static final int OPERATOR = 104;
  public static final int VAR = 100;
  public static final int LBRACE = 101;
  public static final int RBRACE = 102;
  public static final int RBRACK = 13;
  public static final int RPAREN = 11;
  public static final int PATCHES_OWN = 5;
  public static final int LBRACK = 12;
  public static final int IDENTIFIER = 29;
  public static final int END = 8;
  public static final int LPAREN = 10;
  public static final int STRING = 27;
  public static final int EOF = 0;
  public static final int GLOBAL = 2;
  public static final int error = 1;
  public static final int TO = 6;
  public static final int DOUBLE = 28;
  public static final int COLON = 500;
  public static final int EQ = 501;
  public static final int DOT = 502;
  public static final int COMMA = 503;
}

